language: php

before_script:
  - composer self-update
  - composer install --prefer-source

php:
  - 7.4
  - nightly

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

