language: php

before_script:
  - composer self-update
  - composer install

php:
  - 5.5

script:
  - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
