language: php

before_script:
  - composer self-update
  - composer install

php:
  - 5.5
  - hhvm

script: phpunit -c tests/phpunit.xml

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
